spring:
  application:
    name: dododocs
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:~/dododocs;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
oauth:
  github:
    authorize_uri: https://github.com/login/oauth/authorize
    redirect_uri: http://localhost:3000/callback/github
    client_secret: 956682ca8f12648d6c8715460efbf0207578ed37
    token_uri: https://github.com/login/oauth/access_token
    user_uri: https://api.github.com/user
    client_id: Ov23li8DXFjxGqJaQPfq

security:
  jwt:
    token:
      secret_key: secretsecretsecretsecretsecretsecret
      expire_length:
        access_token: 36000000
        refresh_token: 36000000

cloud:
  aws:
    s3:
      bucket: haon-dododocs
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
