name: Sync to fork_dodoBE Repository

on:
  push:
    branches:
      - main  # 원본 레포지토리의 브랜치 이름입니다.

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 원본 레포지토리의 코드를 가져오기
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.KRAMPOLINE_TESTREPOKEY }} # 원본 레포지토리 액세스 토큰

      # Git 사용자 이름과 이메일 설정
      - name: Set up Git user
        run: |
          git config --global user.name "42kko_syncbot"
          git config --global user.email 42kko@example.com
          
      # .github/workflows 디렉토리 삭제
      - name: Remove workflows directory
        run: |
          rm -rf .github/workflows/*
          
      # 타겟 레포지토리에서 .github/workflows 복원
      - name: Restore .github/workflows from target repository
        env:
          TARGET_REPO_TOKEN: ${{ secrets.KRAMPOLINE_TESTREPOKEY }}
        run: |
          git remote add target https://$TARGET_REPO_TOKEN@github.com/42kko/fork_dodoBE.git
          git fetch target main
          git checkout target/main -- .github/workflows
          
      # 타겟 레포지토리 설정 및 강제 푸시
      - name: Force push to target repository
        env:
          TARGET_REPO_TOKEN: ${{ secrets.KRAMPOLINE_TESTREPOKEY }}
        run: |
          git add .
          git commit -m "Sync from source repository, keeping target workflows" || true
          git push https://$TARGET_REPO_TOKEN@github.com/42kko/fork_dodoBE.git main -f
